spring:
  application:
    name: eureka-client
  profiles:
    active: dev
#  cloud:
#    config:
#      uri: https://github.com/ZhangWweihui/springcloud-sample-config.git
#      label: master
#      prefix: ${spring.cloud.config.uri}/${spring.application.name}/${spring.profiles.active}/${spring.cloud.config.label}