server:
  port: 8762

eureka:
  server:
    enable-self-preservation: false #是否开启自我保护
    wait-time-in-ms-when-sync-empty: 0
    peer-node-read-timeout-ms: 3000 #微服务节点连接超时时间
  instance:
    hostname: eureka-server-1
    # prefer-ip-address: true
    # instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka-server:8761/eureka/,http://eureka-server-2:8763/eureka/
    healthcheck:
      enabled: true

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: EurekaServer1
  profiles:
    active: eureka-server-1
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
    client:
      ip-address: 127.0.0.1